FROM eclipse/ubuntu_python:latest
RUN sudo pip install autopep8 Babel certifi chardet configparser decorator docutils future html2text idna jedi Jinja2 json-rpc libsass lxml MarkupSafe mccabe parso passlib Pillow pluggy psutil psycopg2 pycodestyle pydocstyle pyflakes PyPDF2 python-dateutil python-language-server pytz reportlab requests rope six snowballstemmer urllib3 virtualenv Werkzeug yapf 
